##
[Grid]

X1-grid    1    -0.5   128   u    0.5
X2-grid    1    -1.57080   100  u    1.57080
X3-grid    1    -0.5   128   u    0.5


[TimeIntegrator]

CFL              0.8
CFL_max_var      1.1
tstop            130
first_dt         1.e-4
nstages          2

[Hydro]

csiso          constant 1.0
solver         hlld
rotation       1.0
shearingBox    -1.5

[Gravity]
bodyForce      userdef

[Boundary]

X1-beg        shearingbox
X1-end        shearingbox
X2-beg        periodic
X2-end        periodic
X3-beg        periodic
X3-end        periodic

[Setup]

v0           0.00001
# Choice of amplitude
B0           0.05
n	         12
vx-r         0.19
vx-i         0
vy-r         0
vy-i         -0.63
Bx-r         0.72
Bx-i         0
By-r         0
By-i         -0.22


[Output]

dmp        100
vtk        3.0
vtk_slice1 1.0  1  0.0  cut
analysis   0.1
vtk_dir    /home/dp316/dp316/dc-fang1/outputs/MRIShearingBoxNetFlux/MRI_mode_n12_res2x/vtks
dat_dir	 /home/dp316/dp316/dc-fang1/outputs/MRIShearingBoxNetFlux/MRI_mode_n12_res2x/timevol.dat
# File produced automatically by a Perl script
# Do not edit
